### ISSUE TITLE
Add other croissant endpoints

### ISSUE THREAD

**Issue by david4096** [david4096/croissant-rdf#11]
Kaggle and OpenML both expose Croissant JSON-LD. Add the ability to generate RDF from these resources as well. May suggest changing the name of the project

**Comment by bit2424** [comment]
Did not see this one when I proposed the other Issue Open #26, sorry 😭 .

**Comment by bit2424** [comment]
Working on it

**Comment by david4096** [comment]
Closing since we have Kaggle and another issue exists for #42
